# Generated by Django 5.1.6 on 2025-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=10)),
                ('hora', models.TimeField(default='02:00')),
                ('cantidad', models.PositiveIntegerField(default=5)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
