# Generated by Django 5.1.6 on 2025-05-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='cantidad',
            new_name='cantidad_vendida',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
