# Generated by Django 5.1.6 on 2025-05-29 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_cantidad_detalleventa_cantidad_vendida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': True, 'ordering': ['-fecha_venta']},
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='pagina_detalleventa',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='pagina_venta',
        ),
    ]
