# Generated by Django 5.1.6 on 2025-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_configuracionrespaldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('tamano', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Completado', max_length=50)),
                ('archivo', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
