# Generated by Django 5.1.6 on 2025-05-08 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alter_usuario_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contacto',
            field=models.CharField(blank=True, help_text='Número telefónico o contacto adicional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Ingrese su correo electrónico', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(default='0000000000', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento solo puede contener dígitos', regex='^[0-9]+$')]),
        ),
    ]
