# Generated by Django 5.1.6 on 2025-04-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_categoria_proveedor_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
    ]
