# Generated by Django 5.1.7 on 2025-04-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_producto_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
