# Generated by Django 5.1.6 on 2025-05-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='estado',
            field=models.CharField(default='Completado', max_length=20),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tipo',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
