# Generated by Django 5.1.7 on 2025-04-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_proveedor_alter_usuario_options_alter_usuario_table'),
        ('pagina', '0003_alter_usuario_numero_documento'),
    ]

    operations = [
    ]
