# Generated by Django 5.1.6 on 2025-05-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_detalleventa_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
