# Generated by Django 5.1.6 on 2025-05-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_usuario_contacto_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contacto',
        ),
    ]
