# Generated by Django 5.1.6 on 2025-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_backup_estado_alter_backup_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='estado',
            field=models.CharField(default='Completado', max_length=50),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
