# Generated by Django 5.1.6 on 2025-05-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_remove_usuario_contacto'),
    ]

    operations = [
    ]
