# Generated by Django 5.1.6 on 2025-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_remove_proveedor_estado_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código de Barras'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='pagina_producto',
        ),
    ]
