# Generated by Django 5.1.6 on 2025-05-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_backup_estado_alter_backup_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='tamano',
        ),
    ]
