# Generated by Django 5.1.6 on 2025-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
