# Generated by Django 5.1.6 on 2025-06-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_actividadusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadUsuario',
        ),
    ]
