# Generated by Django 5.1.6 on 2025-05-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_actividadusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
    ]
