# Generated by Django 5.1.6 on 2025-05-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_remove_backup_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='tamano',
            field=models.CharField(default='0 MB', max_length=20),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tipo',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
