# Generated by Django 5.1.6 on 2025-06-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_delete_actividadusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit_proveedor',
            field=models.IntegerField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(max_length=15),
        ),
    ]
