# Generated by Django 5.1.6 on 2025-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_backup_tamano_alter_backup_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_salida',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tamano',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
