# Generated by Django 5.1.6 on 2025-05-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_remove_producto_cantidad_salida_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_entrada',
        ),
    ]
