# Generated by Django 5.1.6 on 2025-06-06 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_alter_proveedor_nit_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre de la empresa solo debe contener letras y espacios', regex='^[A-Za-zÁ-ÿ\\s]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit_proveedor',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe contener entre 9 y 11 dígitos', regex='^\\d{9,11}$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener 10 dígitos', regex='^\\d{10}$')]),
        ),
    ]
