# Generated by Django 5.1.6 on 2025-05-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_remove_producto_cantidad_entrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='cantidad_producto',
        ),
    ]
