# Generated by Django 5.1.6 on 2025-06-06 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_alter_proveedor_correo_alter_proveedor_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios', regex='^[A-Za-zÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit_proveedor',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe contener solo números', regex='^\\d+$'), django.core.validators.MinLengthValidator(9, 'El NIT debe tener al menos 9 dígitos')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 10 dígitos', regex='^\\d{10}$')]),
        ),
    ]
