# Generated by Django 5.1.6 on 2025-06-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_alter_proveedor_correo_alter_proveedor_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit_proveedor',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
