# Generated by Django 5.1.6 on 2025-06-09 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_alter_proveedor_nit_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit_proveedor',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe tener entre 9 y 11 dígitos', regex='^\\d{9,11}$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos', regex='^\\d{10}$')]),
        ),
    ]
