# Generated by Django 5.1.6 on 2025-05-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_alter_producto_id_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='pagina_producto',
        ),
    ]
