"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os  # Esto es lo correcto


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=d&cn$=svcwzop_6lw3se#&=w1o&7j_*@nnju69f58kr6pcc!h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    
    'backup',
    'pagina',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'






DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'eltrigal'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'db'),  # <--- debe ser 'db'
        'PORT': os.environ.get('DB_PORT', '3306'), # <--- debe ser '3306'
    }
}
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / "db.sqlite3",
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_TZ = True

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


#Archivos estaticos
STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'pagina/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # <-- Agrega esta línea

LOGIN_REDIRECT_URL = "inicio_inventario"  # ✅ Redirige a inicio_inventario tras iniciar sesión
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'pagina.Usuario'

# Recuperacion de contraseña
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'eltrigalautoservicio3@gmail.com'
EMAIL_HOST_PASSWORD = 'gnxordczmdjkoktj'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'django.core.mail': {
#             'handlers': ['console'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#     },
# }



# settings.py

# 1. IDENTIDAD DEL SITIO
# SITE_NAME = "Autoservicio El Trigal"  # Nombre oficial del negocio
# SITE_DOMAIN = "autoservicioeltrigal.com"  # Dominio principal (sin http/https)
# SITE_URL = "https://www.autoservicioeltrigal.com"  # URL completa

# 2. CONFIGURACIÓN DE CORREOS (EMAILS)
# # Emails genéricos
# DEFAULT_FROM_EMAIL = 'no-reply@autoservicioeltrigal.com'  # Emisor automático
# SERVER_EMAIL = 'errores@autoservicioeltrigal.com'  # Email para notificaciones de errores
# CONTACT_EMAIL = 'contacto@autoservicioeltrigal.com'  # Email público de contacto
# SUPPORT_EMAIL = 'soporte@autoservicioeltrigal.com'  # Soporte técnico

# Personas que recibirán alertas (tu email personal)
ADMINS = [('Oscar Gomez', 'oscarjaviergomez12@gmail.com')]
MANAGERS = ADMINS  # Opcional: puedes definir distintos contactos para managers

# Prefijo para asuntos de emails automáticos
EMAIL_SUBJECT_PREFIX = '[Autoservicio] '
# settings.py
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# 4. TIEMPOS DE EXPIRACIÓN (OPCIONAL)
PASSWORD_RESET_TIMEOUT = 86400  # 24 horas en segundos para links de recuperación


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# COPIAS DE SEGURIDAD
# Datos para backup de MySQL
MYSQL_BACKUP = {
    'USER': 'root',
    'PASSWORD': 'Javier',
    'NAME': 'Proyecto',
}
